/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author ismai
 */
public class TrainSeats extends javax.swing.JFrame {

Train t=new Train();
int i, j;
String id;
ArrayList<String> tri=new ArrayList<String>();
HashMap<String,ArrayList<String>> seatHash=new HashMap<String,ArrayList<String>>();
    /**
     * Creates new form busSeats
     */
public TrainSeats() {
    initComponents();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        four = new javax.swing.JButton();
        two = new javax.swing.JButton();
        thirtyfive = new javax.swing.JButton();
        six = new javax.swing.JButton();
        five = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        ten = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        tweleve = new javax.swing.JButton();
        eleven = new javax.swing.JButton();
        one = new javax.swing.JButton();
        three = new javax.swing.JButton();
        fourteen = new javax.swing.JButton();
        thirteen = new javax.swing.JButton();
        thirtysix = new javax.swing.JButton();
        thirtyfour = new javax.swing.JButton();
        thirtytwo = new javax.swing.JButton();
        thirty = new javax.swing.JButton();
        fifteen = new javax.swing.JButton();
        twentynine = new javax.swing.JButton();
        twentyeight = new javax.swing.JButton();
        thirtyone = new javax.swing.JButton();
        thirtythree = new javax.swing.JButton();
        twentyseven = new javax.swing.JButton();
        twentysix = new javax.swing.JButton();
        twentyfive = new javax.swing.JButton();
        twentyfour = new javax.swing.JButton();
        twentythree = new javax.swing.JButton();
        twentytwo = new javax.swing.JButton();
        sixteen = new javax.swing.JButton();
        seventeen = new javax.swing.JButton();
        eighteen = new javax.swing.JButton();
        ninteen = new javax.swing.JButton();
        twenty = new javax.swing.JButton();
        twentyone = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        four.setBackground(new java.awt.Color(0, 102, 102));
        four.setForeground(new java.awt.Color(0, 102, 102));
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        two.setBackground(new java.awt.Color(0, 102, 102));
        two.setForeground(new java.awt.Color(0, 102, 102));
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        thirtyfive.setBackground(new java.awt.Color(0, 102, 102));
        thirtyfive.setForeground(new java.awt.Color(0, 102, 102));
        thirtyfive.setText("35");
        thirtyfive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtyfiveActionPerformed(evt);
            }
        });

        six.setBackground(new java.awt.Color(0, 102, 102));
        six.setForeground(new java.awt.Color(0, 102, 102));
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        five.setBackground(new java.awt.Color(0, 102, 102));
        five.setForeground(new java.awt.Color(0, 102, 102));
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        seven.setBackground(new java.awt.Color(0, 102, 102));
        seven.setForeground(new java.awt.Color(0, 102, 102));
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        eight.setBackground(new java.awt.Color(0, 102, 102));
        eight.setForeground(new java.awt.Color(0, 102, 102));
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        ten.setBackground(new java.awt.Color(0, 102, 102));
        ten.setForeground(new java.awt.Color(0, 102, 102));
        ten.setText("10");
        ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenActionPerformed(evt);
            }
        });

        nine.setBackground(new java.awt.Color(0, 102, 102));
        nine.setForeground(new java.awt.Color(0, 102, 102));
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        tweleve.setBackground(new java.awt.Color(0, 102, 102));
        tweleve.setForeground(new java.awt.Color(0, 102, 102));
        tweleve.setText("12");
        tweleve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tweleveActionPerformed(evt);
            }
        });

        eleven.setBackground(new java.awt.Color(0, 102, 102));
        eleven.setForeground(new java.awt.Color(0, 102, 102));
        eleven.setText("11");
        eleven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elevenActionPerformed(evt);
            }
        });

        one.setBackground(new java.awt.Color(0, 102, 102));
        one.setForeground(new java.awt.Color(0, 102, 102));
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        three.setBackground(new java.awt.Color(0, 102, 102));
        three.setForeground(new java.awt.Color(0, 102, 102));
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        fourteen.setBackground(new java.awt.Color(0, 102, 102));
        fourteen.setForeground(new java.awt.Color(0, 102, 102));
        fourteen.setText("14");
        fourteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourteenActionPerformed(evt);
            }
        });

        thirteen.setBackground(new java.awt.Color(0, 102, 102));
        thirteen.setForeground(new java.awt.Color(0, 102, 102));
        thirteen.setText("13");
        thirteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirteenActionPerformed(evt);
            }
        });

        thirtysix.setBackground(new java.awt.Color(0, 102, 102));
        thirtysix.setForeground(new java.awt.Color(0, 102, 102));
        thirtysix.setText("36");
        thirtysix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtysixActionPerformed(evt);
            }
        });

        thirtyfour.setBackground(new java.awt.Color(0, 102, 102));
        thirtyfour.setForeground(new java.awt.Color(0, 102, 102));
        thirtyfour.setText("34");
        thirtyfour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtyfourActionPerformed(evt);
            }
        });

        thirtytwo.setBackground(new java.awt.Color(0, 102, 102));
        thirtytwo.setForeground(new java.awt.Color(0, 102, 102));
        thirtytwo.setText("32");
        thirtytwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtytwoActionPerformed(evt);
            }
        });

        thirty.setBackground(new java.awt.Color(0, 102, 102));
        thirty.setForeground(new java.awt.Color(0, 102, 102));
        thirty.setText("30");
        thirty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtyActionPerformed(evt);
            }
        });

        fifteen.setBackground(new java.awt.Color(0, 102, 102));
        fifteen.setForeground(new java.awt.Color(0, 102, 102));
        fifteen.setText("15");
        fifteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteenActionPerformed(evt);
            }
        });

        twentynine.setBackground(new java.awt.Color(0, 102, 102));
        twentynine.setForeground(new java.awt.Color(0, 102, 102));
        twentynine.setText("29");
        twentynine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentynineActionPerformed(evt);
            }
        });

        twentyeight.setBackground(new java.awt.Color(0, 102, 102));
        twentyeight.setForeground(new java.awt.Color(0, 102, 102));
        twentyeight.setText("28");
        twentyeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentyeightActionPerformed(evt);
            }
        });

        thirtyone.setBackground(new java.awt.Color(0, 102, 102));
        thirtyone.setForeground(new java.awt.Color(0, 102, 102));
        thirtyone.setText("31");
        thirtyone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtyoneActionPerformed(evt);
            }
        });

        thirtythree.setBackground(new java.awt.Color(0, 102, 102));
        thirtythree.setForeground(new java.awt.Color(0, 102, 102));
        thirtythree.setText("33");
        thirtythree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtythreeActionPerformed(evt);
            }
        });

        twentyseven.setBackground(new java.awt.Color(0, 102, 102));
        twentyseven.setForeground(new java.awt.Color(0, 102, 102));
        twentyseven.setText("27");
        twentyseven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentysevenActionPerformed(evt);
            }
        });

        twentysix.setBackground(new java.awt.Color(0, 102, 102));
        twentysix.setForeground(new java.awt.Color(0, 102, 102));
        twentysix.setText("26");
        twentysix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentysixActionPerformed(evt);
            }
        });

        twentyfive.setBackground(new java.awt.Color(0, 102, 102));
        twentyfive.setForeground(new java.awt.Color(0, 102, 102));
        twentyfive.setText("25");
        twentyfive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentyfiveActionPerformed(evt);
            }
        });

        twentyfour.setBackground(new java.awt.Color(0, 102, 102));
        twentyfour.setForeground(new java.awt.Color(0, 102, 102));
        twentyfour.setText("24");
        twentyfour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentyfourActionPerformed(evt);
            }
        });

        twentythree.setBackground(new java.awt.Color(0, 102, 102));
        twentythree.setForeground(new java.awt.Color(0, 102, 102));
        twentythree.setText("23");
        twentythree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentythreeActionPerformed(evt);
            }
        });

        twentytwo.setBackground(new java.awt.Color(0, 102, 102));
        twentytwo.setForeground(new java.awt.Color(0, 102, 102));
        twentytwo.setText("22");
        twentytwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentytwoActionPerformed(evt);
            }
        });

        sixteen.setBackground(new java.awt.Color(0, 102, 102));
        sixteen.setForeground(new java.awt.Color(0, 102, 102));
        sixteen.setText("16");
        sixteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixteenActionPerformed(evt);
            }
        });

        seventeen.setBackground(new java.awt.Color(0, 102, 102));
        seventeen.setForeground(new java.awt.Color(0, 102, 102));
        seventeen.setText("17");
        seventeen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seventeenActionPerformed(evt);
            }
        });

        eighteen.setBackground(new java.awt.Color(0, 102, 102));
        eighteen.setForeground(new java.awt.Color(0, 102, 102));
        eighteen.setText("18");
        eighteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eighteenActionPerformed(evt);
            }
        });

        ninteen.setBackground(new java.awt.Color(0, 102, 102));
        ninteen.setForeground(new java.awt.Color(0, 102, 102));
        ninteen.setText("19");
        ninteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ninteenActionPerformed(evt);
            }
        });

        twenty.setBackground(new java.awt.Color(0, 102, 102));
        twenty.setForeground(new java.awt.Color(0, 102, 102));
        twenty.setText("20");
        twenty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentyActionPerformed(evt);
            }
        });

        twentyone.setBackground(new java.awt.Color(0, 102, 102));
        twentyone.setForeground(new java.awt.Color(0, 102, 102));
        twentyone.setText("21");
        twentyone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentyoneActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("        Pick a seat");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sixteen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seventeen)
                                .addGap(9, 9, 9))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(six, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(four, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(two, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fourteen)
                                            .addComponent(eight)
                                            .addComponent(ten, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tweleve, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(thirteen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fifteen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(seven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(five, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(three, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(eleven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(eighteen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ninteen)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(twentythree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(twentyfive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(twentyseven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(twentynine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(thirtyone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(thirtythree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(thirtyfive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(twenty)
                                .addGap(7, 7, 7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(twentyone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(twentytwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(twentyfour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(twentysix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(twentyeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(thirty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(thirtytwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(thirtyfour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(thirtysix)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(thirtysix, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(two, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(thirtyfour, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(thirtyfive)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thirtytwo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four)
                    .addComponent(five)
                    .addComponent(thirtythree, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seven, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(thirty, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(six)
                        .addComponent(thirtyone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eight)
                    .addComponent(nine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(twentyeight, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twentynine, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(twentyseven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(twentysix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eleven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tweleve, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thirteen, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twentyfive, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twentyfour, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourteen, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fifteen, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twentythree, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twentytwo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sixteen, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seventeen, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eighteen, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ninteen, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twenty, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twentyone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void eighteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eighteenActionPerformed
String num = "18"; 
tri=t.returnTrip();
boolean valid=false;
valid=t.seats(5,36,tri,Integer.parseInt(num));
if(valid){
    JOptionPane.showMessageDialog(this, "You bought this ticket!! If you pick another you'll get 50% off");
}
else
{
JOptionPane.showMessageDialog(this, "Seat taken!! please pick another one");

}
    }//GEN-LAST:event_eighteenActionPerformed

    private void ninteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ninteenActionPerformed
String num = "19";       
boolean valid=false;
valid=t.seats(i,j,tri,Integer.parseInt(num));
if(valid){
    JOptionPane.showMessageDialog(this, "You bought this ticket!! If you pick another you'll get 50% off");
}
else
{
JOptionPane.showMessageDialog(this, "Seat taken!! please pick another one");

}
    }//GEN-LAST:event_ninteenActionPerformed

    private void twentyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentyActionPerformed
String num = "20";        
boolean valid=false;
valid=t.seats(i,j,tri,Integer.parseInt(num));
if(valid){
    JOptionPane.showMessageDialog(this, "You bought this ticket!! If you pick another you'll get 50% off");
}
else
{
JOptionPane.showMessageDialog(this, "Seat taken!! please pick another one");

}
    }//GEN-LAST:event_twentyActionPerformed

    private void tweleveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tweleveActionPerformed
String num = "12";        
boolean valid=false;
valid=t.seats(i,j,tri,Integer.parseInt(num));
if(valid){
    JOptionPane.showMessageDialog(this, "You bought this ticket!! If you pick another you'll get 50% off");
}
else
{
JOptionPane.showMessageDialog(this, "Seat taken!! please pick another one");

}
    }//GEN-LAST:event_tweleveActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
String num = "1";     
tri=t.returnTrip();
        if(t.getSeatT()==0){
            i=5;
            j=36;
        }
        else if(t.getSeatT()==1){
            i=6;
            j=36;
        }
        else
        {
            i=7;
            j=36;
        }
        
boolean valid=false;
valid=t.seats(i,j,tri,Integer.parseInt(num));
if(valid){
    JOptionPane.showMessageDialog(this, "You bought this ticket!! If you pick another you'll get 50% off");
}
else
{
JOptionPane.showMessageDialog(this, "Seat taken!! please pick another one");

}
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
String num = "2";         // TODO add your handling code here:
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
String num = "3";         // TODO add your handling code here:
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
String num = "4";         // TODO add your handling code here:
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
String num = "5";         // TODO add your handling code here:
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
String num = "6";         // TODO add your handling code here:
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
String num = "7";         // TODO add your handling code here:
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
String num = "8";         // TODO add your handling code here:
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
String num = "9";         // TODO add your handling code here:
    }//GEN-LAST:event_nineActionPerformed

    private void tenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenActionPerformed
String num = "10";         // TODO add your handling code here:
    }//GEN-LAST:event_tenActionPerformed

    private void elevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elevenActionPerformed
String num = "11";         // TODO add your handling code here:
    }//GEN-LAST:event_elevenActionPerformed

    private void thirteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirteenActionPerformed
String num = "13";         // TODO add your handling code here:
    }//GEN-LAST:event_thirteenActionPerformed

    private void fourteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourteenActionPerformed
String num = "14";         // TODO add your handling code here:
    }//GEN-LAST:event_fourteenActionPerformed

    private void fifteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteenActionPerformed
String num = "15";         // TODO add your handling code here:
    }//GEN-LAST:event_fifteenActionPerformed

    private void sixteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixteenActionPerformed
String num = "16";         // TODO add your handling code here:
    }//GEN-LAST:event_sixteenActionPerformed

    private void seventeenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seventeenActionPerformed
String num = "17";         // TODO add your handling code here:
    }//GEN-LAST:event_seventeenActionPerformed

    private void twentyoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentyoneActionPerformed
String num = "21";         // TODO add your handling code here:
    }//GEN-LAST:event_twentyoneActionPerformed

    private void twentytwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentytwoActionPerformed
String num = "22";         // TODO add your handling code here:
    }//GEN-LAST:event_twentytwoActionPerformed

    private void twentythreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentythreeActionPerformed
String num = "23";         // TODO add your handling code here:
    }//GEN-LAST:event_twentythreeActionPerformed

    private void twentyfourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentyfourActionPerformed
String num = "24";         // TODO add your handling code here:
    }//GEN-LAST:event_twentyfourActionPerformed

    private void twentyfiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentyfiveActionPerformed
String num = "25";         // TODO add your handling code here:
    }//GEN-LAST:event_twentyfiveActionPerformed

    private void twentysixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentysixActionPerformed
String num = "26";         // TODO add your handling code here:
    }//GEN-LAST:event_twentysixActionPerformed

    private void twentysevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentysevenActionPerformed
String num = "27";         // TODO add your handling code here:
    }//GEN-LAST:event_twentysevenActionPerformed

    private void twentyeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentyeightActionPerformed
String num = "28";         // TODO add your handling code here:
    }//GEN-LAST:event_twentyeightActionPerformed

    private void twentynineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentynineActionPerformed
String num = "29";         // TODO add your handling code here:
    }//GEN-LAST:event_twentynineActionPerformed

    private void thirtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtyActionPerformed
String num = "30";         // TODO add your handling code here:
    }//GEN-LAST:event_thirtyActionPerformed

    private void thirtyoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtyoneActionPerformed
String num = "31";         // TODO add your handling code here:
    }//GEN-LAST:event_thirtyoneActionPerformed

    private void thirtytwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtytwoActionPerformed
String num = "32";         // TODO add your handling code here:
    }//GEN-LAST:event_thirtytwoActionPerformed

    private void thirtythreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtythreeActionPerformed
String num = "33";         // TODO add your handling code here:
    }//GEN-LAST:event_thirtythreeActionPerformed

    private void thirtyfourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtyfourActionPerformed
String num = "34";         // TODO add your handling code here:
    }//GEN-LAST:event_thirtyfourActionPerformed

    private void thirtyfiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtyfiveActionPerformed
String num = "35";         // TODO add your handling code here:
    }//GEN-LAST:event_thirtyfiveActionPerformed

    private void thirtysixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtysixActionPerformed
String num = "36";         // TODO add your handling code here:
    }//GEN-LAST:event_thirtysixActionPerformed
void availability(){
    int count=t.availability();
    JOptionPane.showMessageDialog(this,  String.valueOf(count) );
    jLabel2.setText(String.valueOf(count));
     
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainSeats().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eight;
    private javax.swing.JButton eighteen;
    private javax.swing.JButton eleven;
    private javax.swing.JButton fifteen;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton fourteen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nine;
    private javax.swing.JButton ninteen;
    private javax.swing.JButton one;
    private javax.swing.JButton seven;
    private javax.swing.JButton seventeen;
    private javax.swing.JButton six;
    private javax.swing.JButton sixteen;
    private javax.swing.JButton ten;
    private javax.swing.JButton thirteen;
    private javax.swing.JButton thirty;
    private javax.swing.JButton thirtyfive;
    private javax.swing.JButton thirtyfour;
    private javax.swing.JButton thirtyone;
    private javax.swing.JButton thirtysix;
    private javax.swing.JButton thirtythree;
    private javax.swing.JButton thirtytwo;
    private javax.swing.JButton three;
    private javax.swing.JButton tweleve;
    private javax.swing.JButton twenty;
    private javax.swing.JButton twentyeight;
    private javax.swing.JButton twentyfive;
    private javax.swing.JButton twentyfour;
    private javax.swing.JButton twentynine;
    private javax.swing.JButton twentyone;
    private javax.swing.JButton twentyseven;
    private javax.swing.JButton twentysix;
    private javax.swing.JButton twentythree;
    private javax.swing.JButton twentytwo;
    private javax.swing.JButton two;
    // End of variables declaration//GEN-END:variables
}
